language: python
python:
  - '3.8'

addons:
  - firefox: '88.0.1'

branches:
  only:
    - staging

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurrev2_project.settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
  - ./manage.py test substitute.tests.selenium_test
  - ./manage.py test substitute.tests.dbfeed_script_test
