# Generated by Django 3.1.7 on 2021-04-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20210330_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
