# Generated by Django 3.1.7 on 2021-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0006_product_off_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_id',
            field=models.BigIntegerField(),
        ),
    ]
