# Generated by Django 3.1.7 on 2021-05-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0009_product_last_modified_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='off_id',
        ),
    ]
