# Generated by Django 3.1.7 on 2021-03-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brands', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=400)),
                ('ingredients', models.TextField()),
                ('additives', models.CharField(blank=True, max_length=300, null=True)),
                ('allergens', models.CharField(blank=True, max_length=300, null=True)),
                ('nutriscore', models.CharField(blank=True, max_length=1, null=True)),
                ('labels', models.CharField(blank=True, max_length=300, null=True)),
                ('stores', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200)),
                ('compared_to', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ManyToManyField(blank=True, related_name='profiles', to='substitute.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
