# Generated by Django 3.1.7 on 2021-03-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='x', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(default='x', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
