# Generated by Django 3.1.7 on 2021-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_auto_20210323_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
